name: 'deploy'

on:
  push:
    branches: ['main']

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login to ghcr.io'
        uses: docker/login-action@v2
        with:
          registry: 'ghcr.io'
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'
      - name: 'Clone repository'
        uses: actions/checkout@v4
      - name: 'Build app docker image'
        run: |
          IMAGE=$(jq -r '"ghcr.io/\(.author)/\(.name):\(.version)"' package.json)
          docker build --target production -t "$IMAGE" .
      - name: 'Release and push git tag'
        run: "git tag $(jq -r '.version' package.json) && git push --tags"
      - name: 'Create a GitHub release'
        run: "gh release create $(jq -r '.version' package.json) --generate-notes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Push docker image to ghcr.io'
        run: |
          IMAGE=$(jq -r '"ghcr.io/\(.author)/\(.name):\(.version)"' package.json)
          docker push "$IMAGE"
