name: 'integrity'

on:
  pull_request:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: 'Check if image version is available to publish'
        run: './docker/ci/check_version_is_free "$(jq -r ''.version'' package.json)"'
  code:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Copy environment variables'
        run: 'cp .env.dist .env'
      - name: 'Run docker compose environment'
        run: 'docker compose up -d --build --wait --wait-timeout=120'
      - name: 'Run dependency audit'
        run: 'docker compose exec app npm audit'
      - name: 'Run code formatting check'
        run: 'docker compose exec app npm run format'
      - name: 'Run static code analysis'
        run: 'docker compose exec app npm run lint'
      - name: 'Run functional tests'
        run: 'docker compose exec app npm run test:functional'
